// Generated by gencpp from file my_msg/Human.msg
// DO NOT EDIT!


#ifndef MY_MSG_MESSAGE_HUMAN_H
#define MY_MSG_MESSAGE_HUMAN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace my_msg
{
template <class ContainerAllocator>
struct Human_
{
  typedef Human_<ContainerAllocator> Type;

  Human_()
    : id(0)
    , type(0)
    , state(0)
    , pose()  {
    }
  Human_(const ContainerAllocator& _alloc)
    : id(0)
    , type(0)
    , state(0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _id_type;
  _id_type id;

   typedef int64_t _type_type;
  _type_type type;

   typedef int64_t _state_type;
  _state_type state;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::my_msg::Human_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msg::Human_<ContainerAllocator> const> ConstPtr;

}; // struct Human_

typedef ::my_msg::Human_<std::allocator<void> > Human;

typedef boost::shared_ptr< ::my_msg::Human > HumanPtr;
typedef boost::shared_ptr< ::my_msg::Human const> HumanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msg::Human_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msg::Human_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_msg::Human_<ContainerAllocator1> & lhs, const ::my_msg::Human_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.type == rhs.type &&
    lhs.state == rhs.state &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_msg::Human_<ContainerAllocator1> & lhs, const ::my_msg::Human_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_msg::Human_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msg::Human_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msg::Human_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msg::Human_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msg::Human_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msg::Human_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msg::Human_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65b15ba1b364de60fbcac285c6b79d13";
  }

  static const char* value(const ::my_msg::Human_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65b15ba1b364de60ULL;
  static const uint64_t static_value2 = 0xfbcac285c6b79d13ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msg::Human_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msg/Human";
  }

  static const char* value(const ::my_msg::Human_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msg::Human_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 id\n"
"int64 type\n"
"int64 state\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::my_msg::Human_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msg::Human_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.state);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Human_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msg::Human_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msg::Human_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    s << indent << "type: ";
    Printer<int64_t>::stream(s, indent + "  ", v.type);
    s << indent << "state: ";
    Printer<int64_t>::stream(s, indent + "  ", v.state);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSG_MESSAGE_HUMAN_H
