// Generated by gencpp from file my_msg/HumanGazebo.msg
// DO NOT EDIT!


#ifndef MY_MSG_MESSAGE_HUMANGAZEBO_H
#define MY_MSG_MESSAGE_HUMANGAZEBO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace my_msg
{
template <class ContainerAllocator>
struct HumanGazebo_
{
  typedef HumanGazebo_<ContainerAllocator> Type;

  HumanGazebo_()
    : item_name()
    , pose()  {
    }
  HumanGazebo_(const ContainerAllocator& _alloc)
    : item_name(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _item_name_type;
  _item_name_type item_name;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::my_msg::HumanGazebo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msg::HumanGazebo_<ContainerAllocator> const> ConstPtr;

}; // struct HumanGazebo_

typedef ::my_msg::HumanGazebo_<std::allocator<void> > HumanGazebo;

typedef boost::shared_ptr< ::my_msg::HumanGazebo > HumanGazeboPtr;
typedef boost::shared_ptr< ::my_msg::HumanGazebo const> HumanGazeboConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msg::HumanGazebo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msg::HumanGazebo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_msg::HumanGazebo_<ContainerAllocator1> & lhs, const ::my_msg::HumanGazebo_<ContainerAllocator2> & rhs)
{
  return lhs.item_name == rhs.item_name &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_msg::HumanGazebo_<ContainerAllocator1> & lhs, const ::my_msg::HumanGazebo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_msg::HumanGazebo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msg::HumanGazebo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msg::HumanGazebo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msg::HumanGazebo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msg::HumanGazebo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msg::HumanGazebo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msg::HumanGazebo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6a602bef3cc30802df3048df084e986";
  }

  static const char* value(const ::my_msg::HumanGazebo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6a602bef3cc3080ULL;
  static const uint64_t static_value2 = 0x2df3048df084e986ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msg::HumanGazebo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msg/HumanGazebo";
  }

  static const char* value(const ::my_msg::HumanGazebo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msg::HumanGazebo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string item_name\n"
"geometry_msgs/Pose pose\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::my_msg::HumanGazebo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msg::HumanGazebo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.item_name);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HumanGazebo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msg::HumanGazebo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msg::HumanGazebo_<ContainerAllocator>& v)
  {
    s << indent << "item_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.item_name);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSG_MESSAGE_HUMANGAZEBO_H
