// Generated by gencpp from file my_msg/kdangerArray.msg
// DO NOT EDIT!


#ifndef MY_MSG_MESSAGE_KDANGERARRAY_H
#define MY_MSG_MESSAGE_KDANGERARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <my_msg/kdanger.h>

namespace my_msg
{
template <class ContainerAllocator>
struct kdangerArray_
{
  typedef kdangerArray_<ContainerAllocator> Type;

  kdangerArray_()
    : header()
    , items()  {
    }
  kdangerArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , items(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::my_msg::kdanger_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::my_msg::kdanger_<ContainerAllocator> >::other >  _items_type;
  _items_type items;





  typedef boost::shared_ptr< ::my_msg::kdangerArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msg::kdangerArray_<ContainerAllocator> const> ConstPtr;

}; // struct kdangerArray_

typedef ::my_msg::kdangerArray_<std::allocator<void> > kdangerArray;

typedef boost::shared_ptr< ::my_msg::kdangerArray > kdangerArrayPtr;
typedef boost::shared_ptr< ::my_msg::kdangerArray const> kdangerArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msg::kdangerArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msg::kdangerArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_msg::kdangerArray_<ContainerAllocator1> & lhs, const ::my_msg::kdangerArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.items == rhs.items;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_msg::kdangerArray_<ContainerAllocator1> & lhs, const ::my_msg::kdangerArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_msg::kdangerArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msg::kdangerArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msg::kdangerArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msg::kdangerArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msg::kdangerArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msg::kdangerArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msg::kdangerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8821c94651dec6ba6e5aa740d245c31";
  }

  static const char* value(const ::my_msg::kdangerArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8821c94651dec6bULL;
  static const uint64_t static_value2 = 0xa6e5aa740d245c31ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msg::kdangerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msg/kdangerArray";
  }

  static const char* value(const ::my_msg::kdangerArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msg::kdangerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"my_msg/kdanger[] items\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: my_msg/kdanger\n"
"int64 k\n"
"int64[] ids\n"
;
  }

  static const char* value(const ::my_msg::kdangerArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msg::kdangerArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.items);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kdangerArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msg::kdangerArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msg::kdangerArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "items[]" << std::endl;
    for (size_t i = 0; i < v.items.size(); ++i)
    {
      s << indent << "  items[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::my_msg::kdanger_<ContainerAllocator> >::stream(s, indent + "    ", v.items[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSG_MESSAGE_KDANGERARRAY_H
