// Generated by gencpp from file hdl_people_tracking/TrackArray.msg
// DO NOT EDIT!


#ifndef HDL_PEOPLE_TRACKING_MESSAGE_TRACKARRAY_H
#define HDL_PEOPLE_TRACKING_MESSAGE_TRACKARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <hdl_people_tracking/Track.h>

namespace hdl_people_tracking
{
template <class ContainerAllocator>
struct TrackArray_
{
  typedef TrackArray_<ContainerAllocator> Type;

  TrackArray_()
    : header()
    , tracks()  {
    }
  TrackArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tracks(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::hdl_people_tracking::Track_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hdl_people_tracking::Track_<ContainerAllocator> >::other >  _tracks_type;
  _tracks_type tracks;





  typedef boost::shared_ptr< ::hdl_people_tracking::TrackArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hdl_people_tracking::TrackArray_<ContainerAllocator> const> ConstPtr;

}; // struct TrackArray_

typedef ::hdl_people_tracking::TrackArray_<std::allocator<void> > TrackArray;

typedef boost::shared_ptr< ::hdl_people_tracking::TrackArray > TrackArrayPtr;
typedef boost::shared_ptr< ::hdl_people_tracking::TrackArray const> TrackArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hdl_people_tracking::TrackArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hdl_people_tracking::TrackArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hdl_people_tracking::TrackArray_<ContainerAllocator1> & lhs, const ::hdl_people_tracking::TrackArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.tracks == rhs.tracks;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hdl_people_tracking::TrackArray_<ContainerAllocator1> & lhs, const ::hdl_people_tracking::TrackArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hdl_people_tracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hdl_people_tracking::TrackArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hdl_people_tracking::TrackArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdl_people_tracking::TrackArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdl_people_tracking::TrackArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdl_people_tracking::TrackArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdl_people_tracking::TrackArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hdl_people_tracking::TrackArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2c238b988c43cb09ac3d9dbe063b799";
  }

  static const char* value(const ::hdl_people_tracking::TrackArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2c238b988c43cb0ULL;
  static const uint64_t static_value2 = 0x9ac3d9dbe063b799ULL;
};

template<class ContainerAllocator>
struct DataType< ::hdl_people_tracking::TrackArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hdl_people_tracking/TrackArray";
  }

  static const char* value(const ::hdl_people_tracking::TrackArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hdl_people_tracking::TrackArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"Track[] tracks\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: hdl_people_tracking/Track\n"
"int32 id\n"
"float64 age\n"
"geometry_msgs/Point pos\n"
"geometry_msgs/Vector3 vel\n"
"\n"
"float64[9] pos_cov\n"
"float64[9] vel_cov\n"
"\n"
"int64 k\n"
"int64[] ids\n"
"\n"
"hdl_people_tracking/Cluster[] associated\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: hdl_people_tracking/Cluster\n"
"bool is_human\n"
"\n"
"geometry_msgs/Point min_pt\n"
"geometry_msgs/Point max_pt\n"
"geometry_msgs/Vector3 size\n"
"geometry_msgs/Point centroid\n"
;
  }

  static const char* value(const ::hdl_people_tracking::TrackArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hdl_people_tracking::TrackArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tracks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hdl_people_tracking::TrackArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hdl_people_tracking::TrackArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tracks[]" << std::endl;
    for (size_t i = 0; i < v.tracks.size(); ++i)
    {
      s << indent << "  tracks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hdl_people_tracking::Track_<ContainerAllocator> >::stream(s, indent + "    ", v.tracks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDL_PEOPLE_TRACKING_MESSAGE_TRACKARRAY_H
